export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIE = 'FETCH_MOVIE'

export const LOADING = 'LOADING'

export const SAVE_TO_WATCHLIST = 'SAVE_TO_WATCHLIST'
export const FETCH_MOVIES_FROM_WATCHLIST = 'FETCH_MOVIES_FROM_WATCHLIST'